Github pages added
OpenDRR/earthquake-scenarios pull request #16
Opened 2021-11-04 17:02 UTC by DamonU2

- Moved github pages files from data repo to docs folder
- Action to generate release assets when release is created
- Preview maps updated

Once this is merged github pages will need to be enabled using the docs folder

2021-11-04 17:33 UTC, jvanulde commented
@DamonU2 let's set up a meeting with @tieganh to review. This needs some explanation.

2021-11-04 17:37 UTC, jvanulde commented
@tieganh we are moving the gh-pages from the data repo here. The reason being that it allows us finer grained control over what is released and where. It also keeps the scripts that process/access the outputs in this repo. It's much easier to manage than having relevant resources spread across multiple repositories.

2021-11-08 22:07 UTC, jvanulde requested changes
I didn't look at everything but I reviewed the key files. Just one question for you.

2021-11-08 22:25 UTC, DamonU2 commented on docs/_data/dsra.yml
> +    en: Magnitude 9.0 scenario based on complete rupture of the CanSHM6 Hazard Model implementation of the Cascadia Interface Best Fault.
Huh. Not sure how that happened.

2021-11-08 22:28 UTC, DamonU2 commented on docs/_data/dsra.yml
> +    en: Magnitude 9.0 scenario based on complete rupture of the CanSHM6 Hazard Model implementation of the Cascadia Interface Best Fault.
It's just in a weird order. The script to generate that put them alphabetically, so the description is the first thing.

2021-11-10 17:35 UTC, merged